# Generated by Django 2.1 on 2018-11-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('player1', models.CharField(max_length=10)),
                ('player2', models.CharField(max_length=10)),
                ('winner', models.CharField(max_length=10)),
                ('history', models.TextField()),
                ('note', models.CharField(max_length=150)),
            ],
        ),
    ]
